apiVersion: v1
kind: Secret
metadata:
  name: plain-secret
type: Opaque
data:
  DB_ADDRESS: dGVycmFmb3JtLTIwMTgwNTAxMDgzMTQ2NzE4MjAwMDAwMDAxLmN3dWoxbGpjeXMxcy5ldS1jZW50cmFsLTEucmRzLmFtYXpvbmF3cy5jb206NTQzMg==
  DB_USERNAME: dGVycmFmb3Jt
  DB_PASSWORD: XCFENzVYKzdCJHR2RFM5QTBYWmVkdFwhfWc1a3t3Rm1Keg==
